#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FTPServer
version:      1.116
version_from: lib/Net/FTPServer.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
