# Automatically generated by Net-FTPServer.spec.PL


Summary: Net::FTPServer - an extensible, secure FTP server
Name: Net-FTPServer
Version: 0.4.5
Release: 1
Copyright: GPL
Group: Applications/Internet
Source: %{name}-%{version}.tar.gz
BuildRoot: /var/tmp/%{name}-%{version}-root
Requires: Authen-PAM >= 0.10
Requires: BSD-Resource >= 1.08
Requires: Digest-MD5 >= 2.09
Requires: Getopt-Long >= 2.23
Requires: perl >= 5.00503

%description


%prep
%setup -q


%build
perl Makefile.PL
make


%install
rm -rf $RPM_BUILD_ROOT
make PREFIX=$RPM_BUILD_ROOT/usr install
find $RPM_BUILD_ROOT/usr/lib/perl5 -name perllocal.pod -exec rm -f {} \;


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root)
/usr/lib/perl5/man/man3/*
/usr/lib/perl5/site_perl/5.005/Net/FTPServer.pm
/usr/lib/perl5/site_perl/5.005/Net/FTPServer/
/usr/lib/perl5/site_perl/5.005/%{_target}/auto/Net/FTPServer/
